name: tunduk
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  go_router: ^8.2.0
  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/"

# flutter_native_splash:
#   image: assets/icons/tunduk_v2.png


